[package]
authors = ["The Rust Project Developers"]
name = "panic_abort"
version = "0.0.0"

[lib]
path = "lib.rs"
test = false
bench = false
doc = false

[dependencies]
core = { path = "../libcore" }

[target.'cfg(all(unix,not(target_os="none")))'.dependencies]
libc = { path = "../rustc/libc_shim" }
